name: Build & Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add PPA
      run: | 
        sudo apt-add-repository ppa:mir-team/dev
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update

    - name: Install dependencies
      run: |
        sudo apt install gcc-13  g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13
        sudo apt install libmiral-dev libmircore-dev libmircommon-internal-dev libmircommon-dev libmirserver-internal-dev \
          libgtest-dev libyaml-cpp-dev libglib2.0-dev libevdev-dev nlohmann-json3-dev libnotify-dev pcre2-utils \
          libmiroil-dev libmirrenderer-dev libgles2-mesa-dev


    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run:  cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: cd ${{github.workspace}}/build && ./bin/miracle-wm-tests

    - name: Check Licenses
      run: python tools/check_license.py
